development: &development
  adapter: postgresql
  database: portal_development
  username: portal
  timeout: 5000
  encoding: unicode

test: &test
  <<: *development
  database: portal_test

production:
  adapter: postgresql
  database: portal_base
  username: portal_username
  password: portal_password
  timeout: 5000
  encoding: unicode
